name: CI - Build C++ (Visual Studio 2022)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build ProyectoEstructuras
        run: msbuild "Proyecto Estructuras de Datos.sln" /p:Configuration=Release /p:Platform=x64

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            **/x64/Release/*.exe
            **/x64/Release/*.dll
